# Generated by Django 2.0 on 2018-05-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tableentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableEntry',
        ),
        migrations.AlterModelOptions(
            name='alarm',
            options={},
        ),
    ]
