# Generated by Django 2.0 on 2018-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180530_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=100, null=True, verbose_name='地名Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='地名')),
                ('fitst_type', models.CharField(max_length=100, null=True, verbose_name='地址一级类型')),
                ('second_type', models.CharField(max_length=100, null=True, verbose_name='地址二级类型')),
                ('url', models.CharField(max_length=100, null=True, verbose_name='地址详细信息链接')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='定位')),
                ('contact', models.CharField(max_length=100, null=True, verbose_name='联系方式')),
            ],
        ),
    ]
